### ISSUE TITLE
86Box segfaults after libedit install

### ISSUE THREAD

**Issue by ConiKost** [86Box/86Box#3949]
### What happened?

After I only installed libedit (86Box was compiled before having installed libedit), 86Box cannot start anymore and segfaults directly. If I do remove libedit, it starts again fine.

```
[35599.958795] 86Box[1159]: segfault at 308 ip 00007720da8f640f sp 000077209e7fa4f0 error 6 in libedit.so.0.0.70[7720da8e3000+23000] likely on CPU 2 (core 0, socket 0)
[35599.958812] Code: 00 00 4c 8b b7 10 04 00 00 e9 d0 fe ff ff e8 58 cf fe ff 0f 1f 84 00 00 00 00 00 55 31 c0 48 89 e5 41 55 41 54 53 48 83 ec 08 <66> 89 87 08 03 00 00 c5 fe 6f 1d 82 f1 01 00 c5 fe 6f 25 9a f1 01
```

```
SDL: version 2.28.5
86Box monitor console.
Segmentation fault
```

Is there any further way for helping to debug this? This goes beyond my knowledge.

### Configuration file

```ini
None
```

### Operating system

Gentoo Linux

### CPU

Core i7-6600U

### 86Box version

4.0.1

### Build architecture

Linux - x64 (64-bit)

### Build type

- [X] New recompiler
- [ ] Debug build

### Download source

I built 86Box myself (please tell us more about your build configuration)

### Additional context

```
cmake -C /var/tmp/portage/app-emulation/86Box-4.0.1/work/86Box-4.0.1_build/gentoo_common_config.cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DCPPTHREADS=yes -DDEV_BRANCH=yes -DDINPUT=yes -DDYNAREC=ON -DMUNT_EXTERNAL=yes -DFLUIDSYNTH=yes -DMINITRACE=OFF -DMUNT=yes -DNEW_DYNAREC=yes -DOPENAL=yes -DPREFER_STATIC=OFF -DRTMIDI=ON -DQT=no -DRELEASE=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/app-emulation/86Box-4.0.1/work/86Box-4.0.1_build/gentoo_toolchain.cmake /var/tmp/portage/app-emulation/86Box-4.0.1/work/86Box-4.0.1
```

```
dev-libs/libedit-20221030.3.1::gentoo
```

**Comment by OBattler** [comment]
COmpiling a debug binary and running it under GDB should tell you exactly where it segfaults.

**Comment by ConiKost** [comment]
I noticed, that the segfault only ouccurs, when SDL instead of QT is being used (```-DQT=OFF```)

Does this help?

```
(gdb) backtrace
#0  0x00007ffff42b740f in ?? () from /usr/lib64/libedit.so
#1  0x00007ffff42c04c4 in readline () from /usr/lib64/libedit.so
#2  0x0000555555c08a6c in monitor_thread (param=<optimized out>) at /var/tmp/portage/app-emulation/86Box-4.0.1/work/86Box-4.0.1/src/unix/unix.c:890
#3  0x00007ffff751f31f in ?? () from /usr/lib/gcc/x86_64-pc-linux-gnu/13/libstdc++.so.6
#4  0x00007ffff72c6de9 in start_thread () from /lib64/libc.so.6
#5  0x00007ffff73388d8 in clone3 () from /lib64/libc.so.6
```
