### ISSUE TITLE
Bochs VGA causes segfault on Ctrl-Alt-Del

### ISSUE THREAD

**Issue by WinFutureX** [86Box/86Box#4410]
### What happened?

When a machine is configured with the Bochs VGA adapter, it causes the emulator to crash with a segfault when soft rebooting.
```
[  731.011534] main_thread_fn[4610]: segfault at 0 ip 0000000000000000 sp 00007f46721f7778 error 14 in 86Box[400000+28000] likely on CPU 0 (core 0, socket 0)
[  731.011541] Code: Unable to access opcode bytes at 0xffffffffffffffd6.
```
```gdb
(gdb) bt
#0  0x0000000000000000 in ??? ()
#1  0x00000000007fbcc8 in svga_do_render (svga=0x524d7c0)
    at /home/kelsey/86Box/src/video/vid_svga.c:980
#2  0x00000000007feddf in svga_poll (priv=0x524d7c0)
    at /home/kelsey/86Box/src/video/vid_svga.c:1099
#3  0x0000000000445383 in timer_process ()
    at /home/kelsey/86Box/src/timer.c:134
#4  0x0000000000601295 in exec386_dynarec (cycs=<optimized out>)
    at /home/kelsey/86Box/src/cpu/386_dynarec.c:795
#5  0x000000000043d8a0 in pc_run () at /home/kelsey/86Box/src/86box.c:1407
#6  0x00000000008f2aa5 in main_thread_fn ()
    at /home/kelsey/86Box/src/qt/qt_main.cpp:125
#7  0x00007ffff5ee33c3 in execute_native_thread_routine ()
    at /lib64/libstdc++.so.6
#8  0x00007ffff5bcb897 in start_thread () at /lib64/libc.so.6
#9  0x00007ffff5c52a5c in clone3 () at /lib64/libc.so.6

```

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = AMD Ryzen 9 7950X 16-Core Processor
uuid = 34c21b37-6df1-5389-a1f8-9eb5c0c26f18
hide_tool_bar = 1
hide_status_bar = 1
confirm_exit = 0

[Machine]
machine = vpc2007
cpu_family = celeron_mendocino
cpu_speed = 366666666
cpu_multi = 5.5
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
fpu_type = internal
mem_size = 131072

[Video]
gfxcard = bochs_svga

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked
sndcard = es1371

[Storage controllers]
hdc = internal

[Microsoft Virtual PC Network (DECchip 21140 "Tulip FasterNet") #1]
mac = 80:a9:52

[Network]
net_01_card = dec_21140_tulip_vpc
net_01_net_type = slirp

[Hard disks]
hdd_01_parameters = 63, 16, 8320, 0, ide
hdd_01_fn = vbe.img
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_01_turbo = 1
fdd_01_check_bpb = 0
fdd_02_type = none
cdrom_01_speed = 72
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 1:0
cdrom_01_type = 86BOX_CD-ROM_1.00
```

### Operating system

Fedora 39

### CPU

AMD Ryzen 9 7950X

### 86Box version

2e4366de8b2773194176222d1b0a980478280d6f

### Build architecture

Linux - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

I built 86Box myself (please tell us more about your build configuration)

### Additional context

Tried with a different machine/CPU configuration (ATC7020BXII + VIA Cyrix 3 interpreter) and 86Box crashes in the same fashion.

**Comment by WinFutureX** [comment]
The crash still occurs exactly as before. Tested with build 5726 and self-compiled versions.

**Comment by WinFutureX** [comment]
After 656591d3851d480fc72a186fe7e845499cfb8108 I can confirm that the bug is gone and everything is displayed properly. Thank you!
